// Keep placeholder names aligned with the English lookup keys.
export const dynamicCopy: Record<string, Record<string, string>> = {
  fr: {
    "Attribute {number}": "Attribut {number}",
    "{label}. Tap or drag to inspect values; use arrow keys when focused.": "{label}. Touchez ou faites glisser pour explorer les valeurs ; utilisez les flèches du clavier lorsque le graphique est sélectionné.",
    " · {delta}% vs prior": " · {delta} % par rapport à la période précédente", " · partial": " · partiel",
    "No {type} recorded for this transaction.": "Aucune donnée « {type} » enregistrée pour cette transaction.",
    "{count} calls": "{count} appels", "{count} token transfers": "{count} transferts de jetons",
    "updated at #{block}": "mis à jour au bloc #{block}", "No {type} indexed for this address.": "Aucune donnée « {type} » indexée pour cette adresse.",
    "{count} runs": "{count} exécutions", "Source {number}": "Source {number}",
    "{count} source files are included in the verified build.": "{count} fichiers source sont inclus dans la compilation vérifiée.",
    "Token {symbol} {id}": "Jeton {symbol} {id}", "{count} decimals": "{count} décimales",
    "No {type} found.": "Aucun résultat pour « {type} ».",
    "latest {grain}": "dernière période ({grain})", "{count} verified": "{count} vérifiés",
    "{count} AA wallets": "{count} portefeuilles AA", "{value} average": "moyenne : {value}",
    "{count} verified contracts": "{count} contrats vérifiés",
    "{grain} granularity · {count} observations": "Granularité {grain} · {count} observations",
    "Updated {time} · latest interval may be partial": "Mis à jour à {time} · le dernier intervalle peut être incomplet",
    "{grain} TRANSACTIONS · {period}": "TRANSACTIONS · {grain} · {period}", "{count} DAYS": "{count} JOURS",
    "{grain} transactions over {days} days": "Transactions ({grain}) sur {days} jours",
    "{grain} transactions": "Transactions ({grain})", "{count} observations": "{count} observations",
    "{count} DAY RANGE": "PÉRIODE DE {count} JOURS", "{grain} active accounts": "Comptes actifs ({grain})",
    "Synced to {network}": "Synchronisé avec {network}", "{network} node behind": "Nœud {network} en retard",
    "Syncing {network}": "Synchronisation de {network}", "{network} node unavailable": "Nœud {network} indisponible",
    "Checked {time} · refreshes every five seconds": "Vérifié à {time} · actualisation toutes les cinq secondes",
    "safe at {block}": "bloc sécurisé : {block}", "{count} block lag": "retard de {count} blocs",
    "{count} on Ink block topic": "{count} sur le canal des blocs Ink", "{count} in routing table": "{count} dans la table de routage",
    "Last block {count} seconds ago": "Dernier bloc il y a {count} secondes",
    "{ready}/{total} upstreams ready": "{ready}/{total} sources en amont prêtes",
    "used of {total}": "utilisés sur {total}", "{percent}% used": "{percent} % utilisés",
  },
  es: {
    "Attribute {number}": "Atributo {number}",
    "{label}. Tap or drag to inspect values; use arrow keys when focused.": "{label}. Toca o arrastra para ver los valores; usa las flechas del teclado cuando el gráfico tenga el foco.",
    " · {delta}% vs prior": " · {delta} % frente al período anterior", " · partial": " · parcial",
    "No {type} recorded for this transaction.": "No hay datos de «{type}» registrados para esta transacción.",
    "{count} calls": "{count} llamadas", "{count} token transfers": "{count} transferencias de tokens",
    "updated at #{block}": "actualizado en el bloque #{block}", "No {type} indexed for this address.": "No hay datos de «{type}» indexados para esta dirección.",
    "{count} runs": "{count} ejecuciones", "Source {number}": "Fuente {number}",
    "{count} source files are included in the verified build.": "La compilación verificada incluye {count} archivos fuente.",
    "Token {symbol} {id}": "Token {symbol} {id}", "{count} decimals": "{count} decimales",
    "No {type} found.": "No se encontraron datos de «{type}».",
    "latest {grain}": "último período ({grain})", "{count} verified": "{count} verificados",
    "{count} AA wallets": "{count} carteras AA", "{value} average": "promedio: {value}",
    "{count} verified contracts": "{count} contratos verificados",
    "{grain} granularity · {count} observations": "Granularidad {grain} · {count} observaciones",
    "Updated {time} · latest interval may be partial": "Actualizado a las {time} · el último intervalo puede estar incompleto",
    "{grain} TRANSACTIONS · {period}": "TRANSACCIONES · {grain} · {period}", "{count} DAYS": "{count} DÍAS",
    "{grain} transactions over {days} days": "Transacciones ({grain}) durante {days} días",
    "{grain} transactions": "Transacciones ({grain})", "{count} observations": "{count} observaciones",
    "{count} DAY RANGE": "PERÍODO DE {count} DÍAS", "{grain} active accounts": "Cuentas activas ({grain})",
    "Synced to {network}": "Sincronizado con {network}", "{network} node behind": "Nodo de {network} atrasado",
    "Syncing {network}": "Sincronizando {network}", "{network} node unavailable": "Nodo de {network} no disponible",
    "Checked {time} · refreshes every five seconds": "Comprobado a las {time} · se actualiza cada cinco segundos",
    "safe at {block}": "bloque seguro: {block}", "{count} block lag": "retraso de {count} bloques",
    "{count} on Ink block topic": "{count} en el canal de bloques de Ink", "{count} in routing table": "{count} en la tabla de enrutamiento",
    "Last block {count} seconds ago": "Último bloque hace {count} segundos",
    "{ready}/{total} upstreams ready": "{ready}/{total} servidores de origen listos",
    "used of {total}": "utilizados de {total}", "{percent}% used": "{percent} % utilizado",
  },
  pt: {
    "Attribute {number}": "Atributo {number}",
    "{label}. Tap or drag to inspect values; use arrow keys when focused.": "{label}. Toque ou arraste para ver os valores; use as setas do teclado quando o gráfico estiver em foco.",
    " · {delta}% vs prior": " · {delta}% em relação ao período anterior", " · partial": " · parcial",
    "No {type} recorded for this transaction.": "Não há dados de «{type}» registrados para esta transação.",
    "{count} calls": "{count} chamadas", "{count} token transfers": "{count} transferências de tokens",
    "updated at #{block}": "atualizado no bloco #{block}", "No {type} indexed for this address.": "Não há dados de «{type}» indexados para este endereço.",
    "{count} runs": "{count} execuções", "Source {number}": "Fonte {number}",
    "{count} source files are included in the verified build.": "A compilação verificada inclui {count} arquivos de código-fonte.",
    "Token {symbol} {id}": "Token {symbol} {id}", "{count} decimals": "{count} decimais",
    "No {type} found.": "Nenhum dado de «{type}» encontrado.",
    "latest {grain}": "último período ({grain})", "{count} verified": "{count} verificados",
    "{count} AA wallets": "{count} carteiras AA", "{value} average": "média: {value}",
    "{count} verified contracts": "{count} contratos verificados",
    "{grain} granularity · {count} observations": "Granularidade {grain} · {count} observações",
    "Updated {time} · latest interval may be partial": "Atualizado às {time} · o último intervalo pode estar incompleto",
    "{grain} TRANSACTIONS · {period}": "TRANSAÇÕES · {grain} · {period}", "{count} DAYS": "{count} DIAS",
    "{grain} transactions over {days} days": "Transações ({grain}) em {days} dias",
    "{grain} transactions": "Transações ({grain})", "{count} observations": "{count} observações",
    "{count} DAY RANGE": "PERÍODO DE {count} DIAS", "{grain} active accounts": "Contas ativas ({grain})",
    "Synced to {network}": "Sincronizado com {network}", "{network} node behind": "Nó de {network} atrasado",
    "Syncing {network}": "Sincronizando {network}", "{network} node unavailable": "Nó de {network} indisponível",
    "Checked {time} · refreshes every five seconds": "Verificado às {time} · atualiza a cada cinco segundos",
    "safe at {block}": "bloco seguro: {block}", "{count} block lag": "atraso de {count} blocos",
    "{count} on Ink block topic": "{count} no canal de blocos da Ink", "{count} in routing table": "{count} na tabela de roteamento",
    "Last block {count} seconds ago": "Último bloco há {count} segundos",
    "{ready}/{total} upstreams ready": "{ready}/{total} serviços upstream prontos",
    "used of {total}": "usados de {total}", "{percent}% used": "{percent}% usado",
  },
  zh: {
    "Attribute {number}": "属性 {number}",
    "{label}. Tap or drag to inspect values; use arrow keys when focused.": "{label}。点击或拖动以查看数值；图表获得焦点后可使用方向键。",
    " · {delta}% vs prior": " · 较上一期 {delta}%", " · partial": " · 数据未完整",
    "No {type} recorded for this transaction.": "这笔交易没有记录{type}。",
    "{count} calls": "{count} 次调用", "{count} token transfers": "{count} 笔代币转账",
    "updated at #{block}": "更新于区块 #{block}", "No {type} indexed for this address.": "此地址没有已索引的{type}记录。",
    "{count} runs": "运行 {count} 次", "Source {number}": "源文件 {number}",
    "{count} source files are included in the verified build.": "已验证的构建包含 {count} 个源文件。",
    "Token {symbol} {id}": "代币 {symbol} {id}", "{count} decimals": "{count} 位小数",
    "No {type} found.": "未找到{type}。",
    "latest {grain}": "最近一期（{grain}）", "{count} verified": "{count} 个已验证",
    "{count} AA wallets": "{count} 个 AA 钱包", "{value} average": "平均 {value}",
    "{count} verified contracts": "{count} 个已验证合约",
    "{grain} granularity · {count} observations": "{grain}粒度 · {count} 个观测值",
    "Updated {time} · latest interval may be partial": "更新于 {time} · 最近一期数据可能不完整",
    "{grain} TRANSACTIONS · {period}": "交易 · {grain} · {period}", "{count} DAYS": "{count} 天",
    "{grain} transactions over {days} days": "过去 {days} 天的交易（{grain}）",
    "{grain} transactions": "交易（{grain}）", "{count} observations": "{count} 个观测值",
    "{count} DAY RANGE": "{count} 天范围", "{grain} active accounts": "活跃账户（{grain}）",
    "Synced to {network}": "已与 {network} 同步", "{network} node behind": "{network} 节点落后",
    "Syncing {network}": "正在同步 {network}", "{network} node unavailable": "{network} 节点不可用",
    "Checked {time} · refreshes every five seconds": "检查于 {time} · 每五秒刷新",
    "safe at {block}": "安全区块：{block}", "{count} block lag": "落后 {count} 个区块",
    "{count} on Ink block topic": "Ink 区块主题上有 {count} 个节点", "{count} in routing table": "路由表中有 {count} 个节点",
    "Last block {count} seconds ago": "上一个区块出现在 {count} 秒前",
    "{ready}/{total} upstreams ready": "{ready}/{total} 个上游服务就绪",
    "used of {total}": "已使用，总量 {total}", "{percent}% used": "已使用 {percent}%",
  },
  ja: {
    "Attribute {number}": "属性 {number}",
    "{label}. Tap or drag to inspect values; use arrow keys when focused.": "{label}。タップまたはドラッグして値を確認できます。フォーカス中は矢印キーを使用してください。",
    " · {delta}% vs prior": " · 前期比 {delta}%", " · partial": " · 一部未確定",
    "No {type} recorded for this transaction.": "このトランザクションには{type}の記録がありません。",
    "{count} calls": "{count} 件の呼び出し", "{count} token transfers": "{count} 件のトークン転送",
    "updated at #{block}": "ブロック #{block} で更新", "No {type} indexed for this address.": "このアドレスには{type}の索引済み記録がありません。",
    "{count} runs": "{count} 回実行", "Source {number}": "ソース {number}",
    "{count} source files are included in the verified build.": "検証済みのビルドには {count} 個のソースファイルが含まれます。",
    "Token {symbol} {id}": "トークン {symbol} {id}", "{count} decimals": "小数点以下 {count} 桁",
    "No {type} found.": "{type}が見つかりません。",
    "latest {grain}": "最新期間（{grain}）", "{count} verified": "検証済み {count} 件",
    "{count} AA wallets": "AA ウォレット {count} 件", "{value} average": "平均 {value}",
    "{count} verified contracts": "検証済みコントラクト {count} 件",
    "{grain} granularity · {count} observations": "{grain}単位 · 観測値 {count} 件",
    "Updated {time} · latest interval may be partial": "{time} に更新 · 最新期間のデータは不完全な場合があります",
    "{grain} TRANSACTIONS · {period}": "トランザクション · {grain} · {period}", "{count} DAYS": "{count} 日間",
    "{grain} transactions over {days} days": "過去 {days} 日のトランザクション（{grain}）",
    "{grain} transactions": "トランザクション（{grain}）", "{count} observations": "観測値 {count} 件",
    "{count} DAY RANGE": "{count} 日間の範囲", "{grain} active accounts": "アクティブアカウント（{grain}）",
    "Synced to {network}": "{network} と同期済み", "{network} node behind": "{network} ノードが遅延しています",
    "Syncing {network}": "{network} を同期中", "{network} node unavailable": "{network} ノードを利用できません",
    "Checked {time} · refreshes every five seconds": "{time} に確認 · 5 秒ごとに更新",
    "safe at {block}": "安全ブロック：{block}", "{count} block lag": "{count} ブロック遅延",
    "{count} on Ink block topic": "Ink ブロックトピックに {count} ピア", "{count} in routing table": "ルーティングテーブルに {count} ピア",
    "Last block {count} seconds ago": "最後のブロックは {count} 秒前",
    "{ready}/{total} upstreams ready": "上流サービス {ready}/{total} 件が準備完了",
    "used of {total}": "使用済み / 総容量 {total}", "{percent}% used": "{percent}% 使用済み",
  },
  ru: {
    "Attribute {number}": "Атрибут {number}",
    "{label}. Tap or drag to inspect values; use arrow keys when focused.": "{label}. Нажмите или перетащите, чтобы просмотреть значения; при фокусе используйте клавиши со стрелками.",
    " · {delta}% vs prior": " · {delta}% к предыдущему периоду", " · partial": " · неполные данные",
    "No {type} recorded for this transaction.": "Для этой транзакции нет записей «{type}».",
    "{count} calls": "Вызовов: {count}", "{count} token transfers": "Переводов токенов: {count}",
    "updated at #{block}": "обновлено в блоке #{block}", "No {type} indexed for this address.": "Для этого адреса нет проиндексированных записей «{type}».",
    "{count} runs": "Запусков: {count}", "Source {number}": "Исходный файл {number}",
    "{count} source files are included in the verified build.": "В проверенную сборку входят исходные файлы: {count}.",
    "Token {symbol} {id}": "Токен {symbol} {id}", "{count} decimals": "Знаков после запятой: {count}",
    "No {type} found.": "Записи «{type}» не найдены.",
    "latest {grain}": "последний период ({grain})", "{count} verified": "Проверено: {count}",
    "{count} AA wallets": "AA-кошельков: {count}", "{value} average": "среднее: {value}",
    "{count} verified contracts": "Проверенных контрактов: {count}",
    "{grain} granularity · {count} observations": "Периодичность: {grain} · наблюдений: {count}",
    "Updated {time} · latest interval may be partial": "Обновлено в {time} · последний интервал может быть неполным",
    "{grain} TRANSACTIONS · {period}": "ТРАНЗАКЦИИ · {grain} · {period}", "{count} DAYS": "ДНЕЙ: {count}",
    "{grain} transactions over {days} days": "Транзакции за {days} дней ({grain})",
    "{grain} transactions": "Транзакции ({grain})", "{count} observations": "Наблюдений: {count}",
    "{count} DAY RANGE": "ПЕРИОД: {count} ДНЕЙ", "{grain} active accounts": "Активные аккаунты ({grain})",
    "Synced to {network}": "Синхронизировано с {network}", "{network} node behind": "Узел {network} отстаёт",
    "Syncing {network}": "Синхронизация {network}", "{network} node unavailable": "Узел {network} недоступен",
    "Checked {time} · refreshes every five seconds": "Проверено в {time} · обновление каждые пять секунд",
    "safe at {block}": "безопасный блок: {block}", "{count} block lag": "отставание: {count} блоков",
    "{count} on Ink block topic": "В теме блоков Ink: {count}", "{count} in routing table": "В таблице маршрутизации: {count}",
    "Last block {count} seconds ago": "Последний блок был {count} секунд назад",
    "{ready}/{total} upstreams ready": "Вышестоящих сервисов готово: {ready}/{total}",
    "used of {total}": "использовано из {total}", "{percent}% used": "Использовано {percent}%",
  },
  hi: {
    "Attribute {number}": "विशेषता {number}",
    "{label}. Tap or drag to inspect values; use arrow keys when focused.": "{label}। मान देखने के लिए टैप या ड्रैग करें; फ़ोकस होने पर तीर कुंजियों का उपयोग करें।",
    " · {delta}% vs prior": " · पिछली अवधि से {delta}%", " · partial": " · आंशिक",
    "No {type} recorded for this transaction.": "इस लेन-देन के लिए {type} का कोई रिकॉर्ड नहीं है।",
    "{count} calls": "{count} कॉल", "{count} token transfers": "{count} टोकन ट्रांसफ़र",
    "updated at #{block}": "ब्लॉक #{block} पर अपडेट", "No {type} indexed for this address.": "इस पते के लिए {type} का कोई इंडेक्स रिकॉर्ड नहीं है।",
    "{count} runs": "{count} रन", "Source {number}": "स्रोत {number}",
    "{count} source files are included in the verified build.": "सत्यापित बिल्ड में {count} स्रोत फ़ाइलें हैं।",
    "Token {symbol} {id}": "टोकन {symbol} {id}", "{count} decimals": "{count} दशमलव स्थान",
    "No {type} found.": "{type} नहीं मिला।",
    "latest {grain}": "नवीनतम अवधि ({grain})", "{count} verified": "{count} सत्यापित",
    "{count} AA wallets": "{count} AA वॉलेट", "{value} average": "औसत: {value}",
    "{count} verified contracts": "{count} सत्यापित कॉन्ट्रैक्ट",
    "{grain} granularity · {count} observations": "{grain} अंतराल · {count} अवलोकन",
    "Updated {time} · latest interval may be partial": "{time} पर अपडेट · नवीनतम अंतराल अधूरा हो सकता है",
    "{grain} TRANSACTIONS · {period}": "लेन-देन · {grain} · {period}", "{count} DAYS": "{count} दिन",
    "{grain} transactions over {days} days": "पिछले {days} दिनों के लेन-देन ({grain})",
    "{grain} transactions": "लेन-देन ({grain})", "{count} observations": "{count} अवलोकन",
    "{count} DAY RANGE": "{count} दिनों की अवधि", "{grain} active accounts": "सक्रिय खाते ({grain})",
    "Synced to {network}": "{network} से सिंक", "{network} node behind": "{network} नोड पीछे है",
    "Syncing {network}": "{network} सिंक हो रहा है", "{network} node unavailable": "{network} नोड उपलब्ध नहीं है",
    "Checked {time} · refreshes every five seconds": "{time} पर जाँचा गया · हर पाँच सेकंड में अपडेट",
    "safe at {block}": "सुरक्षित ब्लॉक: {block}", "{count} block lag": "{count} ब्लॉक पीछे",
    "{count} on Ink block topic": "Ink ब्लॉक टॉपिक पर {count}", "{count} in routing table": "रूटिंग तालिका में {count}",
    "Last block {count} seconds ago": "पिछला ब्लॉक {count} सेकंड पहले",
    "{ready}/{total} upstreams ready": "{ready}/{total} अपस्ट्रीम सेवाएँ तैयार",
    "used of {total}": "{total} में से उपयोग", "{percent}% used": "{percent}% उपयोग हुआ",
  },
  ar: {
    "Attribute {number}": "السمة {number}",
    "{label}. Tap or drag to inspect values; use arrow keys when focused.": "{label}. انقر أو اسحب لفحص القيم؛ استخدم مفاتيح الأسهم عند التركيز على الرسم.",
    " · {delta}% vs prior": " · {delta}% مقارنة بالفترة السابقة", " · partial": " · بيانات جزئية",
    "No {type} recorded for this transaction.": "لا توجد سجلات «{type}» لهذه المعاملة.",
    "{count} calls": "{count} استدعاءات", "{count} token transfers": "{count} تحويلات للرموز",
    "updated at #{block}": "حُدّث عند الكتلة #{block}", "No {type} indexed for this address.": "لا توجد سجلات «{type}» مفهرسة لهذا العنوان.",
    "{count} runs": "{count} عمليات تشغيل", "Source {number}": "المصدر {number}",
    "{count} source files are included in the verified build.": "يتضمن البناء المتحقق منه {count} ملفات مصدر.",
    "Token {symbol} {id}": "الرمز {symbol} {id}", "{count} decimals": "{count} منازل عشرية",
    "No {type} found.": "لم يُعثر على «{type}».",
    "latest {grain}": "أحدث فترة ({grain})", "{count} verified": "{count} متحقق منها",
    "{count} AA wallets": "{count} محافظ AA", "{value} average": "المتوسط: {value}",
    "{count} verified contracts": "{count} عقود متحقق منها",
    "{grain} granularity · {count} observations": "فاصل {grain} · {count} مشاهدات",
    "Updated {time} · latest interval may be partial": "تحديث عند {time} · قد تكون بيانات الفترة الأخيرة غير مكتملة",
    "{grain} TRANSACTIONS · {period}": "المعاملات · {grain} · {period}", "{count} DAYS": "{count} أيام",
    "{grain} transactions over {days} days": "المعاملات خلال {days} يومًا ({grain})",
    "{grain} transactions": "المعاملات ({grain})", "{count} observations": "{count} مشاهدات",
    "{count} DAY RANGE": "فترة {count} يومًا", "{grain} active accounts": "الحسابات النشطة ({grain})",
    "Synced to {network}": "متزامن مع {network}", "{network} node behind": "عقدة {network} متأخرة",
    "Syncing {network}": "جارٍ مزامنة {network}", "{network} node unavailable": "عقدة {network} غير متاحة",
    "Checked {time} · refreshes every five seconds": "فُحص عند {time} · يُحدّث كل خمس ثوانٍ",
    "safe at {block}": "الكتلة الآمنة: {block}", "{count} block lag": "تأخر بمقدار {count} كتل",
    "{count} on Ink block topic": "{count} في موضوع كتل Ink", "{count} in routing table": "{count} في جدول التوجيه",
    "Last block {count} seconds ago": "آخر كتلة قبل {count} ثانية",
    "{ready}/{total} upstreams ready": "{ready}/{total} مصادر بيانات جاهزة",
    "used of {total}": "مستخدم من إجمالي {total}", "{percent}% used": "المستخدم {percent}%",
  },
  bn: {
    "Attribute {number}": "বৈশিষ্ট্য {number}",
    "{label}. Tap or drag to inspect values; use arrow keys when focused.": "{label}। মান দেখতে ট্যাপ বা টেনে নিন; ফোকাস থাকলে তীরচিহ্নের কী ব্যবহার করুন।",
    " · {delta}% vs prior": " · আগের সময়ের তুলনায় {delta}%", " · partial": " · আংশিক",
    "No {type} recorded for this transaction.": "এই লেনদেনের জন্য {type}-এর কোনো রেকর্ড নেই।",
    "{count} calls": "{count}টি কল", "{count} token transfers": "{count}টি টোকেন স্থানান্তর",
    "updated at #{block}": "ব্লক #{block}-এ হালনাগাদ", "No {type} indexed for this address.": "এই ঠিকানার জন্য {type}-এর কোনো ইনডেক্স করা রেকর্ড নেই।",
    "{count} runs": "{count} বার চালানো হয়েছে", "Source {number}": "সোর্স {number}",
    "{count} source files are included in the verified build.": "যাচাইকৃত বিল্ডে {count}টি সোর্স ফাইল আছে।",
    "Token {symbol} {id}": "টোকেন {symbol} {id}", "{count} decimals": "{count} দশমিক স্থান",
    "No {type} found.": "{type} পাওয়া যায়নি।",
    "latest {grain}": "সর্বশেষ সময়কাল ({grain})",
    "{count} verified": "{count}টি যাচাইকৃত",
    "{count} AA wallets": "{count}টি AA ওয়ালেট", "{value} average": "গড়: {value}",
    "{count} verified contracts": "{count}টি যাচাইকৃত কন্ট্র্যাক্ট",
    "{grain} granularity · {count} observations": "{grain} ব্যবধান · {count}টি পর্যবেক্ষণ",
    "Updated {time} · latest interval may be partial": "{time}-এ হালনাগাদ · সর্বশেষ ব্যবধানের তথ্য অসম্পূর্ণ হতে পারে",
    "{grain} TRANSACTIONS · {period}": "লেনদেন · {grain} · {period}", "{count} DAYS": "{count} দিন",
    "{grain} transactions over {days} days": "গত {days} দিনের লেনদেন ({grain})",
    "{grain} transactions": "লেনদেন ({grain})", "{count} observations": "{count}টি পর্যবেক্ষণ",
    "{count} DAY RANGE": "{count} দিনের সময়সীমা", "{grain} active accounts": "সক্রিয় অ্যাকাউন্ট ({grain})",
    "Synced to {network}": "{network}-এর সঙ্গে সিঙ্ক হয়েছে", "{network} node behind": "{network} নোড পিছিয়ে আছে",
    "Syncing {network}": "{network} সিঙ্ক হচ্ছে", "{network} node unavailable": "{network} নোড পাওয়া যাচ্ছে না",
    "Checked {time} · refreshes every five seconds": "{time}-এ পরীক্ষা করা হয়েছে · প্রতি পাঁচ সেকেন্ডে হালনাগাদ",
    "safe at {block}": "নিরাপদ ব্লক: {block}", "{count} block lag": "{count} ব্লক পিছিয়ে",
    "{count} on Ink block topic": "Ink ব্লক টপিকে {count}টি", "{count} in routing table": "রাউটিং টেবিলে {count}টি",
    "Last block {count} seconds ago": "সর্বশেষ ব্লক {count} সেকেন্ড আগে",
    "{ready}/{total} upstreams ready": "{ready}/{total}টি আপস্ট্রিম প্রস্তুত",
    "used of {total}": "মোট {total} থেকে ব্যবহৃত", "{percent}% used": "{percent}% ব্যবহৃত",
  },
};
