export const explorerCopy: Record<string, Record<string, string>> = {
  en: {
    "Raw value": "Raw value",
    "solidity-hardhat": "Solidity · Hardhat build info",
    "solidity-foundry": "Solidity · Foundry build info",
    "standard-input": "Solidity · compiler JSON",
    "vyper-standard-input": "Vyper · compiler JSON",
    "flattened-code": "Solidity · single file",
    "vyper-code": "Vyper · single file",
    "multi-part": "Solidity · multiple files",
    "vyper-multi-part": "Vyper · multiple files",
    sourcify: "Sourcify lookup",
    slow: "Low priority",
    average: "Standard",
    fast: "High priority",
  },
  fr: {
    "Raw value": "Valeur brute",
    "Unable to read source file": "Impossible de lire le fichier source",
    "Total batches": "Nombre de lots",
    "Total games": "Nombre de litiges",
    "solidity-hardhat": "Solidity · compilation Hardhat",
    "solidity-foundry": "Solidity · compilation Foundry",
    "Generate build information with your project’s original compiler settings, then upload its build-info JSON here. The input is extracted without changing compilation settings.":
      "Générez les informations de compilation avec les paramètres originaux du projet, puis chargez le JSON build-info ici. L’entrée sera extraite sans modifier ces paramètres.",
    "Partially verified": "Vérification partielle",
    "Verified at": "Date de vérification",
    "Download source": "Télécharger la source",
    "Compiler settings": "Paramètres de compilation",
    "Creation bytecode": "Code de création",
    "Deployed bytecode": "Code déployé",
    "Incomplete interval": "Intervalle incomplet",
    "Label appearance and link (optional)":
      "Apparence et lien de l’étiquette (facultatifs)",
    "Label URL": "Lien de l’étiquette",
    "Label icon URL": "URL de l’icône",
    "Background (Hex)": "Fond (hexadécimal)",
    "Text (Hex)": "Texte (hexadécimal)",
    "Label description (max 80 characters)":
      "Description de l’étiquette (80 caractères maximum)",
    "Additional label": "Étiquette supplémentaire",
    "Remove label": "Supprimer l’étiquette",
    "Add label": "Ajouter une étiquette",
    "Verification method": "Méthode de vérification",
    "standard-input": "Solidity · JSON de compilation",
    "vyper-standard-input": "Vyper · JSON de compilation",
    "flattened-code": "Solidity · fichier unique",
    "vyper-code": "Vyper · fichier unique",
    "multi-part": "Solidity · plusieurs fichiers",
    "vyper-multi-part": "Vyper · plusieurs fichiers",
    sourcify: "Recherche Sourcify",
    "Source files": "Fichiers source",
    "Source code": "Code source",
    "EVM version": "Version EVM",
    "Enable optimizer": "Activer l’optimiseur",
    "Optimizer runs": "Nombre d’exécutions de l’optimiseur",
    "Linked libraries (JSON name to address)":
      "Bibliothèques liées (JSON du nom vers l’adresse)",
    "Look up existing verified compiler metadata in Sourcify. No source upload is needed.":
      "Recherchez les données de compilation déjà vérifiées dans Sourcify. Aucun fichier source n’est nécessaire.",
    "File names in sources must preserve the paths used by imports. Edit the JSON above if needed.":
      "Les noms de fichiers doivent conserver les chemins des imports. Modifiez le JSON ci-dessus si nécessaire.",
    "All statistics": "Toutes les statistiques",
    "View chart": "Voir le graphique",
    "Domain history": "Historique du domaine",
    "L1 transaction": "Transaction L1",
    "Reverted — no balance movement": "Appel annulé — aucun mouvement de solde",
    "The operation’s execution log range is unavailable.":
      "La plage de journaux de cette opération est indisponible.",
    "Records are limited to this operation’s execution log range.":
      "Seuls les journaux correspondant à l’exécution de cette opération sont affichés.",
    "No matching records on this page; continue to the next page.":
      "Aucun résultat correspondant sur cette page ; consultez la suivante.",
    "Explorer tools": "Outils de l’explorer",
    "Top accounts": "Principaux comptes",
    "Internal transactions": "Transactions internes",
    "Token transfers": "Transferts de jetons",
    "Transaction batches": "Lots de transactions",
    "Transaction batch": "Lot de transactions",
    "Dispute games": "Litiges",
    "Name services": "Noms de domaine",
    "Gas tracker": "Suivi du gas",
    Dapps: "Applications",
    "Verify contract": "Vérifier un contrat",
    "Submit public tag": "Proposer une étiquette publique",
    Page: "Page",
    Newest: "Plus récents",
    Previous: "Précédente",
    Next: "Suivante",
    "Share of supply": "Part de l’offre",
    Type: "Type",
    Storage: "Stockage",
    "L1 transactions": "Transactions L1",
    "L2 blocks": "Blocs L2",
    "Batch ID": "Identifiant du lot",
    "First L2 block": "Premier bloc L2",
    "Last L2 block": "Dernier bloc L2",
    "Dispute games challenge L2 output claims on Ethereum. Their contract addresses belong to L1.":
      "Les litiges contestent les engagements de la chaîne L2 sur Ethereum. Leurs contrats se trouvent sur L1.",
    "L1 contract": "Contrat L1",
    "Game type": "Type de litige",
    "L2 timestamp": "Date L2",
    Created: "Créé",
    Resolved: "Résolu",
    "In progress": "En cours",
    "Defender wins": "Défenseur gagnant",
    "Challenger wins": "Contestataire gagnant",
    "Gas estimates describe L2 execution. The total transaction fee also includes the L1 data fee.":
      "Les estimations concernent l’exécution L2. Les frais totaux comprennent aussi les frais de données L1.",
    slow: "Priorité basse",
    average: "Standard",
    fast: "Priorité haute",
    "Estimated inclusion": "Inclusion estimée",
    "Priority fee": "Frais de priorité",
    Updated: "Actualisé",
    "Gas price history": "Historique du prix du gas",
    "How gas fees work": "Comprendre les frais de gas",
    "Execution uses gas multiplied by the effective gas price. L1 data fees pay for publishing rollup data to Ethereum. Open a transaction to inspect both components.":
      "Les frais d’exécution correspondent au gas consommé multiplié par son prix effectif. Les frais de données L1 financent leur publication sur Ethereum. Ouvrez une transaction pour consulter les deux composantes.",
    "User operation": "Opération utilisateur",
    Sender: "Expéditeur",
    Bundler: "Agrégateur de transactions",
    Paymaster: "Payeur des frais",
    Factory: "Contrat de création",
    "Call gas limit": "Limite de gas d’appel",
    "Verification gas limit": "Limite de gas de vérification",
    "Pre-verification gas": "Gas avant vérification",
    "Decoded call": "Appel décodé",
    "Decoded execution": "Exécution décodée",
    "Raw operation": "Opération brute",
    "Names may be registered on another chain. Address links show the selected Ink network.":
      "Les noms peuvent être enregistrés sur une autre chaîne. Les liens d’adresse affichent le réseau Ink sélectionné.",
    "Domain name": "Nom de domaine",
    Protocol: "Protocole",
    "All protocols": "Tous les protocoles",
    "Resolved address": "Adresse associée",
    Registered: "Enregistré",
    Expires: "Expiration",
    "Domain details": "Détails du domaine",
    Category: "Catégorie",
    "All categories": "Toutes les catégories",
    Author: "Auteur",
    Rating: "Évaluation",
    "Open app": "Ouvrir l’application",
    "Account history": "Historique du compte",
    "Balance change": "Variation du solde",
    "Historical ETH balance": "Solde ETH historique",
    "Asset flows": "Flux d’actifs",
    "Transfers on this transaction": "Transferts de cette transaction",
    "No balance history indexed.": "Aucun historique de solde indexé.",
    Asset: "Actif",
    Amount: "Quantité",
    "base units": "unités de base",
    Transfer: "Transfert",
    "Indexed native and token movements are shown separately. Execution fees are displayed in transaction details.":
      "Les mouvements natifs et les transferts de jetons indexés sont affichés séparément. Les frais d’exécution sont indiqués dans les détails de la transaction.",
    "Verify deployed bytecode against its original compiler input. Successful verification publishes the source code.":
      "Comparez le code déployé à ses données de compilation originales. Une vérification réussie publie le code source.",
    "Contract address": "Adresse du contrat",
    "Standard input JSON": "Entrée de compilation JSON",
    "Compiler version": "Version du compilateur",
    License: "Licence",
    "Contract name (optional)": "Nom du contrat (facultatif)",
    "Detect constructor arguments automatically":
      "Détecter automatiquement les arguments du constructeur",
    "Constructor arguments (hex)": "Arguments du constructeur (hexadécimal)",
    "I authorize publishing these contract sources for verification.":
      "J’autorise la publication de ces sources pour leur vérification.",
    "Verification in progress": "Vérification en cours",
    "Verify & publish source": "Vérifier et publier les sources",
    "Source verified": "Sources vérifiées",
    "Verification failed": "Échec de la vérification",
    "Verification pending": "Vérification en attente",
    "View contract source": "Voir les sources du contrat",
    "Check result": "Vérifier le résultat",
    "Invalid standard input JSON": "Entrée JSON de compilation invalide",
    "Include source files in standard input":
      "Incluez les fichiers sources dans les données de compilation",
    "Confirm source publication and provide a valid contract address":
      "Confirmez la publication des sources et indiquez une adresse de contrat valide",
    "Standard input exceeds 2 MiB":
      "Les données de compilation dépassent 2 Mio",
    "Proposals are reviewed by this explorer’s operators before public display. Contact details are kept in the private review queue.":
      "Les propositions sont examinées par les opérateurs de cet explorer avant publication. Vos coordonnées restent dans la file privée de modération.",
    "Your name": "Votre nom",
    Email: "E-mail",
    "Company name": "Nom de l’entreprise",
    "Company website": "Site de l’entreprise",
    "Contract or account address": "Adresse du contrat ou du compte",
    "Label (35 characters maximum)": "Étiquette (35 caractères maximum)",
    "Tag type": "Type d’étiquette",
    "Explain the connection between the address and label":
      "Expliquez le lien entre l’adresse et l’étiquette",
    "I agree to the review of my contact details and public display of the approved address label.":
      "J’accepte l’examen de mes coordonnées et la publication de l’étiquette approuvée.",
    "Submitting request": "Envoi en cours",
    "Send request": "Envoyer la proposition",
    "Request received; awaiting review":
      "Proposition reçue, en attente de modération",
    Reference: "Référence",
    "View address": "Voir l’adresse",
    "Public labels": "Étiquettes publiques",
    "Raw log data": "Données brutes du journal",
    "Decoded event": "Événement décodé",
    "Company details (optional)": "Informations sur l’entreprise (facultatif)",
    "Number of accounts": "Nombre de comptes",
    "Cumulative account growth over time": "Évolution du nombre total de comptes",
    "Active accounts number per period": "Nombre de comptes actifs sur la période",
    "Number of newly added accounts": "Nombre de nouveaux comptes",
    "Average transaction fee": "Frais moyens par transaction",
    "Average amount of ETH spent on gas fees per transaction": "Montant moyen des frais de gas en ETH par transaction",
    "New transactions": "Nouvelles transactions",
    "Number of new transactions": "Nombre de nouvelles transactions",
    "Transaction fees": "Frais de transaction",
    "Sum of ETH spent on gas fees": "Total des frais de gas en ETH",
    "Number of transactions": "Nombre de transactions",
    "Cumulative transaction growth over time": "Évolution du nombre total de transactions",
    "Transaction success rate": "Taux de réussite des transactions",
    "Success rate for all included transactions": "Part des transactions incluses qui ont réussi",
    "New EIP-7702 authorizations": "Nouvelles autorisations EIP-7702",
    "Number of new EIP-7702 authorizations": "Nombre de nouvelles autorisations EIP-7702",
    "Number of EIP-7702 authorizations": "Nombre d’autorisations EIP-7702",
    "Cumulative EIP-7702 authorization growth over time": "Évolution du nombre total d’autorisations EIP-7702",
    "Average block rewards": "Récompense moyenne par bloc",
    "Average amount of reward": "Montant moyen des récompenses",
    "Average block size": "Taille moyenne des blocs",
    "Space (in bytes) taken up by all block fields": "Espace occupé par les blocs, en octets",
    "Number of new blocks added to the chain": "Nombre de nouveaux blocs ajoutés à la chaîne",
    "Number of ETH transfers": "Nombre de transferts ETH",
    "Completed token transfers": "Transferts de jetons exécutés",
    "Average gas limit": "Limite de gas moyenne",
    "Average block gas limit": "Limite de gas moyenne par bloc",
    "Average gas price": "Prix moyen du gas",
    "Average price (Gwei) per unit of gas": "Prix moyen par unité de gas, en Gwei",
    "Total gas usage": "Gas consommé au total",
    "Cumulative gas used over time": "Consommation cumulée de gas",
    "Network utilization": "Utilisation du réseau",
    "Percentage of gas used compared to the gas limit": "Part du gas consommé par rapport à la limite",
    "Average gas used": "Gas consommé en moyenne",
    "Average amount of gas used per block": "Consommation moyenne de gas par bloc",
    "Number of contracts": "Nombre de contrats",
    "Cumulative contract growth over time": "Évolution du nombre total de contrats",
    "New contracts": "Nouveaux contrats",
    "Number of new contracts in the network": "Nombre de nouveaux contrats sur le réseau",
    "New verified contracts": "Nouveaux contrats vérifiés",
    "Number of newly verified contracts": "Nombre de contrats récemment vérifiés",
    "Number of verified contracts": "Nombre de contrats vérifiés",
    "Cumulative verified contract growth over time": "Évolution du nombre total de contrats vérifiés",
    "User operations": "Opérations utilisateur",
    "Number of user operations": "Nombre d’opérations utilisateur",
    "Cumulative user operation (ERC-4337) growth over time": "Évolution du nombre total d’opérations ERC-4337",
    "New user operations": "Nouvelles opérations utilisateur",
    "Number of new user operations as per the ERC-4337 standard": "Nombre de nouvelles opérations ERC-4337",
    "New AA wallets": "Nouveaux comptes abstraits",
    "Number of newly added account abstraction wallets (ERC-4337)": "Nombre de nouveaux comptes ERC-4337",
    "Number of AA wallets": "Nombre de comptes abstraits",
    "Cumulative account abstraction wallets (ERC-4337) growth over time": "Évolution du nombre total de comptes ERC-4337",
    "Active AA wallets": "Comptes abstraits actifs",
    "Active account abstraction wallets (ERC-4337) number per period": "Nombre de comptes ERC-4337 actifs sur la période",
    "Active bundlers": "Agrégateurs actifs",
    "Active user ops bundlers number per period": "Nombre d’agrégateurs actifs sur la période",
    "Active paymasters": "Payeurs de frais actifs",
    "Active user ops paymasters number per period": "Nombre de payeurs de frais actifs sur la période",
  },
};
