export const walletCopy: Record<string, Record<string, string>> = {
  "en": {
    "chooseWallet": "Choose a wallet",
    "browserWallet": "Browser wallet",
    "noInstalledWallet": "No installed wallet was detected.",
    "walletBrowserHelp": "On your phone, open this page inside your wallet’s browser. On a computer, install a wallet extension, then retry.",
    "approvalAmount": "Amount",
    "New blocks": "New blocks",
    "walletConnectQr": "WalletConnect · QR code",
    "walletScanQr": "Scan with your mobile wallet and approve the connection.",
    "walletOpenMobile": "Open mobile wallet",
    "walletConnectUnconfigured": "WalletConnect is not configured. Contact the site operator.",
    "walletConnectOriginDenied": "WalletConnect has not authorized this site. Contact the site operator.",
    "walletConnectUnavailable": "WalletConnect is unavailable. Check your connection and try again.",
    "walletConnectExpired": "Connection expired. Try again.",
    "walletWrongNetwork": "Select an account on this network.",
    "approvalsTitle": "Token approvals",
    "approvalsIntro": "Inspect ERC-20 and NFT permissions. Connect the owner’s wallet to revoke them.",
    "approvalRevoke": "Revoke",
    "approvalSpender": "Authorized spender / operator",
    "approvalActive": "Active",
    "approvalAll": "All permissions",
    "approvalRevoked": "Inactive",
    "approvalUnknown": "State unavailable",
    "approvalStateUnavailable": "Permission could not be verified on chain. Retry before revoking.",
    "approvalUnlimited": "Unlimited",
    "approvalRaw": "raw units",
    "approvalAccess": "Access",
    "approvalCollection": "All NFTs in this collection",
    "approvalSingleNft": "This NFT only",
    "approvalUseWallet": "Inspect connected wallet",
    "approvalWrongOwner": "Only the owner’s wallet can revoke these permissions.",
    "approvalNone": "No matching active permission found in the indexed standard events.",
    "approvalHistoryIncomplete": "The history scan is incomplete. Retry to check the remaining permissions.",
    "approvalScanned": "History checked through block {block} / {total}. Reading current permissions…",
    "approvalRevokeReview": "This transaction removes only this permission. The wallet confirms the network fee.",
    "approvalScope": "Discovery uses standard Approval / ApprovalForAll events from the index; current state is read on chain. Non-standard contracts, unindexed events and Permit2 permissions are outside this scan.",
    "liveHttp": "LIVE · HTTP",
    "cancel": "Cancel"
  },
  "fr": {
    "chooseWallet": "Choisir un portefeuille",
    "browserWallet": "Portefeuille du navigateur",
    "noInstalledWallet": "Aucun portefeuille installé n’a été détecté.",
    "walletBrowserHelp": "Sur téléphone, ouvrez cette page dans le navigateur de votre portefeuille. Sur ordinateur, installez une extension de portefeuille, puis réessayez.",
    "approvalAmount": "Quantité",
    "New blocks": "Nouveaux blocs",
    "walletConnectQr": "WalletConnect · QR code",
    "walletScanQr": "Scannez avec votre portefeuille mobile et confirmez la connexion.",
    "walletOpenMobile": "Ouvrir le portefeuille mobile",
    "walletConnectUnconfigured": "WalletConnect n’est pas configuré. Contactez le responsable du site.",
    "walletConnectOriginDenied": "WalletConnect n’a pas autorisé ce site. Contactez le responsable du site.",
    "walletConnectUnavailable": "WalletConnect est indisponible. Vérifiez votre connexion et réessayez.",
    "walletConnectExpired": "La connexion a expiré. Réessayez.",
    "walletWrongNetwork": "Sélectionnez un compte sur ce réseau.",
    "approvalsTitle": "Autorisations des jetons",
    "approvalsIntro": "Consultez les permissions ERC-20 et NFT. Connectez le portefeuille propriétaire pour les révoquer.",
    "approvalRevoke": "Révoquer",
    "approvalSpender": "Bénéficiaire / opérateur autorisé",
    "approvalActive": "Actives",
    "approvalAll": "Toutes les permissions",
    "approvalRevoked": "Inactives",
    "approvalUnknown": "État indisponible",
    "approvalStateUnavailable": "La permission n’a pas pu être vérifiée sur la chaîne. Réessayez avant de révoquer.",
    "approvalUnlimited": "Illimité",
    "approvalRaw": "unités brutes",
    "approvalAccess": "Accès",
    "approvalCollection": "Tous les NFT de cette collection",
    "approvalSingleNft": "Ce NFT uniquement",
    "approvalUseWallet": "Consulter le portefeuille connecté",
    "approvalWrongOwner": "Seul le portefeuille propriétaire peut révoquer ces permissions.",
    "approvalNone": "Aucune permission active correspondante dans les événements standards indexés.",
    "approvalHistoryIncomplete": "L’analyse de l’historique est incomplète. Réessayez pour vérifier les permissions restantes.",
    "approvalScanned": "Historique analysé jusqu’au bloc {block} / {total}. Lecture des permissions actuelles…",
    "approvalRevokeReview": "Cette transaction retire uniquement cette permission. Le portefeuille confirme les frais réseau.",
    "approvalScope": "La recherche utilise les événements standards Approval / ApprovalForAll de l’index ; l’état actuel est relu sur la chaîne. Les contrats non standards, événements non indexés et permissions Permit2 ne sont pas couverts.",
    "liveHttp": "DIRECT · HTTP",
    "cancel": "Annuler"
  },
  "es": {
    "chooseWallet": "Elegir una cartera",
    "browserWallet": "Cartera del navegador",
    "noInstalledWallet": "No se detectó ninguna cartera instalada.",
    "walletBrowserHelp": "En tu teléfono, abre esta página en el navegador de tu cartera. En un ordenador, instala una extensión de cartera y vuelve a intentarlo.",
    "approvalAmount": "Cantidad",
    "New blocks": "Nuevos bloques",
    "walletConnectQr": "WalletConnect · código QR",
    "walletScanQr": "Escanea con tu cartera móvil y aprueba la conexión.",
    "walletOpenMobile": "Abrir cartera móvil",
    "walletConnectUnconfigured": "WalletConnect no está configurado. Contacta al administrador.",
    "walletConnectOriginDenied": "WalletConnect no ha autorizado este sitio. Contacta al administrador.",
    "walletConnectUnavailable": "WalletConnect no está disponible. Comprueba tu conexión e inténtalo de nuevo.",
    "walletConnectExpired": "La conexión caducó. Inténtalo de nuevo.",
    "walletWrongNetwork": "Selecciona una cuenta en esta red.",
    "approvalsTitle": "Permisos de tokens",
    "approvalsIntro": "Consulta permisos ERC-20 y NFT. Conecta la cartera del propietario para revocarlos.",
    "approvalRevoke": "Revocar",
    "approvalSpender": "Beneficiario / operador autorizado",
    "approvalActive": "Activos",
    "approvalAll": "Todos los permisos",
    "approvalRevoked": "Inactivos",
    "approvalUnknown": "Estado no disponible",
    "approvalStateUnavailable": "No se pudo verificar el permiso en la cadena. Reintenta antes de revocar.",
    "approvalUnlimited": "Ilimitado",
    "approvalRaw": "unidades mínimas",
    "approvalAccess": "Acceso",
    "approvalCollection": "Todos los NFT de esta colección",
    "approvalSingleNft": "Solo este NFT",
    "approvalUseWallet": "Consultar cartera conectada",
    "approvalWrongOwner": "Solo la cartera del propietario puede revocar estos permisos.",
    "approvalNone": "No hay permisos activos correspondientes en los eventos estándar indexados.",
    "approvalHistoryIncomplete": "El análisis del historial está incompleto. Reintenta para comprobar el resto.",
    "approvalScanned": "Historial revisado hasta el bloque {block} / {total}. Leyendo permisos actuales…",
    "approvalRevokeReview": "Esta transacción elimina solo este permiso. La cartera confirma la comisión de red.",
    "approvalScope": "La búsqueda usa eventos estándar Approval / ApprovalForAll del índice; el estado actual se lee en la cadena. Contratos no estándar, eventos no indexados y permisos Permit2 quedan fuera.",
    "liveHttp": "EN VIVO · HTTP",
    "cancel": "Cancelar"
  },
  "pt": {
    "chooseWallet": "Escolher uma carteira",
    "browserWallet": "Carteira do navegador",
    "noInstalledWallet": "Nenhuma carteira instalada foi detectada.",
    "walletBrowserHelp": "No celular, abra esta página no navegador da sua carteira. No computador, instale uma extensão de carteira e tente novamente.",
    "approvalAmount": "Quantidade",
    "New blocks": "Novos blocos",
    "walletConnectQr": "WalletConnect · código QR",
    "walletScanQr": "Leia com sua carteira móvel e aprove a conexão.",
    "walletOpenMobile": "Abrir carteira móvel",
    "walletConnectUnconfigured": "WalletConnect não está configurado. Contate o administrador.",
    "walletConnectOriginDenied": "WalletConnect não autorizou este site. Contate o administrador.",
    "walletConnectUnavailable": "WalletConnect está indisponível. Verifique sua conexão e tente novamente.",
    "walletConnectExpired": "A conexão expirou. Tente novamente.",
    "walletWrongNetwork": "Selecione uma conta nesta rede.",
    "approvalsTitle": "Permissões de tokens",
    "approvalsIntro": "Consulte permissões ERC-20 e NFT. Conecte a carteira do proprietário para revogá-las.",
    "approvalRevoke": "Revogar",
    "approvalSpender": "Beneficiário / operador autorizado",
    "approvalActive": "Ativas",
    "approvalAll": "Todas as permissões",
    "approvalRevoked": "Inativas",
    "approvalUnknown": "Estado indisponível",
    "approvalStateUnavailable": "Não foi possível verificar a permissão na rede. Tente novamente antes de revogar.",
    "approvalUnlimited": "Ilimitado",
    "approvalRaw": "unidades brutas",
    "approvalAccess": "Acesso",
    "approvalCollection": "Todos os NFTs desta coleção",
    "approvalSingleNft": "Somente este NFT",
    "approvalUseWallet": "Consultar carteira conectada",
    "approvalWrongOwner": "Só a carteira do proprietário pode revogar estas permissões.",
    "approvalNone": "Nenhuma permissão ativa correspondente nos eventos padrão indexados.",
    "approvalHistoryIncomplete": "A análise do histórico está incompleta. Tente novamente para verificar o restante.",
    "approvalScanned": "Histórico verificado até o bloco {block} / {total}. Lendo permissões atuais…",
    "approvalRevokeReview": "Esta transação remove apenas esta permissão. A carteira confirma a taxa de rede.",
    "approvalScope": "A busca usa eventos padrão Approval / ApprovalForAll do índice; o estado atual é lido na rede. Contratos não padrão, eventos não indexados e permissões Permit2 não são cobertos.",
    "liveHttp": "AO VIVO · HTTP",
    "cancel": "Cancelar"
  },
  "zh": {
    "chooseWallet": "选择钱包",
    "browserWallet": "浏览器钱包",
    "noInstalledWallet": "未检测到已安装的钱包。",
    "walletBrowserHelp": "在手机上，请使用钱包内置浏览器打开此页面。在电脑上，请安装钱包扩展后重试。",
    "approvalAmount": "数量",
    "New blocks": "新区块",
    "walletConnectQr": "WalletConnect · 二维码",
    "walletScanQr": "用手机钱包扫描并批准连接。",
    "walletOpenMobile": "打开手机钱包",
    "walletConnectUnconfigured": "WalletConnect 尚未配置，请联系网站管理员。",
    "walletConnectOriginDenied": "WalletConnect 尚未授权此网站，请联系网站管理员。",
    "walletConnectUnavailable": "WalletConnect 暂不可用，请检查网络连接后重试。",
    "walletConnectExpired": "连接已过期，请重试。",
    "walletWrongNetwork": "请选择此网络的账户。",
    "approvalsTitle": "代币授权",
    "approvalsIntro": "查看 ERC-20 和 NFT 授权。连接所有者钱包以撤销。",
    "approvalRevoke": "撤销",
    "approvalSpender": "获授权的支出方 / 操作员",
    "approvalActive": "有效",
    "approvalAll": "全部授权",
    "approvalRevoked": "无效",
    "approvalUnknown": "状态不可用",
    "approvalStateUnavailable": "无法在链上验证授权。撤销前请重试。",
    "approvalUnlimited": "无限",
    "approvalRaw": "原始单位",
    "approvalAccess": "权限范围",
    "approvalCollection": "此集合中的所有 NFT",
    "approvalSingleNft": "仅此 NFT",
    "approvalUseWallet": "查看已连接钱包",
    "approvalWrongOwner": "只有所有者的钱包才能撤销这些授权。",
    "approvalNone": "已索引的标准事件中未找到匹配的有效授权。",
    "approvalHistoryIncomplete": "历史扫描未完成。请重试以检查其余授权。",
    "approvalScanned": "历史已检查至区块 {block} / {total}。正在读取当前授权…",
    "approvalRevokeReview": "此交易仅移除此授权。钱包将确认网络费用。",
    "approvalScope": "通过索引中的标准 Approval / ApprovalForAll 事件发现授权，链上读取当前状态。不涵盖非标准合约、未索引事件或 Permit2 授权。",
    "liveHttp": "实时 · HTTP",
    "cancel": "取消"
  },
  "hi": {
    "chooseWallet": "वॉलेट चुनें",
    "browserWallet": "ब्राउज़र वॉलेट",
    "noInstalledWallet": "कोई इंस्टॉल किया गया वॉलेट नहीं मिला।",
    "walletBrowserHelp": "फ़ोन पर यह पेज अपने वॉलेट के ब्राउज़र में खोलें। कंप्यूटर पर वॉलेट एक्सटेंशन इंस्टॉल करें और फिर से प्रयास करें।",
    "approvalAmount": "राशि",
    "New blocks": "नए ब्लॉक",
    "walletConnectQr": "WalletConnect · QR कोड",
    "walletScanQr": "मोबाइल वॉलेट से स्कैन करके कनेक्शन स्वीकार करें।",
    "walletOpenMobile": "मोबाइल वॉलेट खोलें",
    "walletConnectUnconfigured": "WalletConnect कॉन्फ़िगर नहीं है। साइट संचालक से संपर्क करें।",
    "walletConnectOriginDenied": "WalletConnect ने इस साइट को अनुमति नहीं दी है। साइट संचालक से संपर्क करें।",
    "walletConnectUnavailable": "WalletConnect उपलब्ध नहीं है। अपना कनेक्शन जाँचें और फिर से प्रयास करें।",
    "walletConnectExpired": "कनेक्शन समाप्त हो गया। फिर प्रयास करें।",
    "walletWrongNetwork": "इस नेटवर्क पर खाता चुनें।",
    "approvalsTitle": "टोकन अनुमतियाँ",
    "approvalsIntro": "ERC-20 और NFT अनुमतियाँ देखें। रद्द करने के लिए मालिक का वॉलेट जोड़ें।",
    "approvalRevoke": "रद्द करें",
    "approvalSpender": "अधिकृत खर्चकर्ता / ऑपरेटर",
    "approvalActive": "सक्रिय",
    "approvalAll": "सभी अनुमतियाँ",
    "approvalRevoked": "निष्क्रिय",
    "approvalUnknown": "स्थिति उपलब्ध नहीं",
    "approvalStateUnavailable": "चेन पर अनुमति सत्यापित नहीं हुई। रद्द करने से पहले फिर प्रयास करें।",
    "approvalUnlimited": "असीमित",
    "approvalRaw": "मूल इकाइयाँ",
    "approvalAccess": "पहुँच",
    "approvalCollection": "इस संग्रह के सभी NFT",
    "approvalSingleNft": "केवल यह NFT",
    "approvalUseWallet": "जुड़ा वॉलेट देखें",
    "approvalWrongOwner": "केवल मालिक का वॉलेट ये अनुमतियाँ रद्द कर सकता है।",
    "approvalNone": "इंडेक्स किए गए मानक घटनाओं में सक्रिय अनुमति नहीं मिली।",
    "approvalHistoryIncomplete": "इतिहास की जाँच अधूरी है। बाकी अनुमतियों के लिए फिर प्रयास करें।",
    "approvalScanned": "ब्लॉक {block} / {total} तक इतिहास जाँचा। वर्तमान अनुमतियाँ पढ़ रहे हैं…",
    "approvalRevokeReview": "यह लेनदेन केवल यह अनुमति हटाता है। वॉलेट नेटवर्क शुल्क की पुष्टि करता है।",
    "approvalScope": "इंडेक्स के मानक Approval / ApprovalForAll घटनाओं से खोज; वर्तमान स्थिति चेन से पढ़ी जाती है। गैर-मानक कॉन्ट्रैक्ट, गैर-इंडेक्स घटनाएँ और Permit2 शामिल नहीं हैं।",
    "liveHttp": "लाइव · HTTP",
    "cancel": "रद्द करें"
  },
  "ar": {
    "chooseWallet": "اختيار محفظة",
    "browserWallet": "محفظة المتصفح",
    "noInstalledWallet": "لم يتم العثور على محفظة مثبتة.",
    "walletBrowserHelp": "على الهاتف، افتح هذه الصفحة داخل متصفح محفظتك. على الكمبيوتر، ثبّت إضافة محفظة ثم حاول مجدداً.",
    "approvalAmount": "الكمية",
    "New blocks": "الكتل الجديدة",
    "walletConnectQr": "WalletConnect · رمز QR",
    "walletScanQr": "امسح بمحفظتك المحمولة ووافق على الاتصال.",
    "walletOpenMobile": "فتح المحفظة المحمولة",
    "walletConnectUnconfigured": "لم يتم إعداد WalletConnect. تواصل مع مشغل الموقع.",
    "walletConnectOriginDenied": "لم يسمح WalletConnect لهذا الموقع. تواصل مع مشغل الموقع.",
    "walletConnectUnavailable": "WalletConnect غير متاح. تحقق من اتصالك وحاول مجدداً.",
    "walletConnectExpired": "انتهت مهلة الاتصال. حاول مجدداً.",
    "walletWrongNetwork": "اختر حساباً على هذه الشبكة.",
    "approvalsTitle": "أذونات الرموز",
    "approvalsIntro": "راجع أذونات ERC-20 وNFT. اربط محفظة المالك لإلغائها.",
    "approvalRevoke": "إلغاء",
    "approvalSpender": "المنفق / المشغل المصرّح له",
    "approvalActive": "نشطة",
    "approvalAll": "جميع الأذونات",
    "approvalRevoked": "غير نشطة",
    "approvalUnknown": "الحالة غير متاحة",
    "approvalStateUnavailable": "تعذر التحقق من الإذن على السلسلة. أعد المحاولة قبل الإلغاء.",
    "approvalUnlimited": "غير محدود",
    "approvalRaw": "وحدات خام",
    "approvalAccess": "الوصول",
    "approvalCollection": "جميع NFT في هذه المجموعة",
    "approvalSingleNft": "هذا NFT فقط",
    "approvalUseWallet": "فحص المحفظة المتصلة",
    "approvalWrongOwner": "محفظة المالك وحدها تستطيع إلغاء هذه الأذونات.",
    "approvalNone": "لا توجد أذونات نشطة مطابقة في الأحداث القياسية المفهرسة.",
    "approvalHistoryIncomplete": "فحص السجل غير مكتمل. أعد المحاولة للتحقق من الأذونات المتبقية.",
    "approvalScanned": "تم فحص السجل حتى الكتلة {block} / {total}. تُقرأ الأذونات الحالية…",
    "approvalRevokeReview": "تزيل هذه المعاملة هذا الإذن فقط. تؤكد المحفظة رسوم الشبكة.",
    "approvalScope": "يعتمد الاكتشاف على أحداث Approval / ApprovalForAll القياسية المفهرسة، والحالة الحالية تُقرأ على السلسلة. لا يشمل العقود غير القياسية والأحداث غير المفهرسة وأذونات Permit2.",
    "liveHttp": "مباشر · HTTP",
    "cancel": "إلغاء"
  },
  "bn": {
    "chooseWallet": "ওয়ালেট বেছে নিন",
    "browserWallet": "ব্রাউজারের ওয়ালেট",
    "noInstalledWallet": "কোনো ইনস্টল করা ওয়ালেট পাওয়া যায়নি।",
    "walletBrowserHelp": "ফোনে এই পৃষ্ঠা আপনার ওয়ালেটের ব্রাউজারে খুলুন। কম্পিউটারে ওয়ালেট এক্সটেনশন ইনস্টল করে আবার চেষ্টা করুন।",
    "approvalAmount": "পরিমাণ",
    "New blocks": "নতুন ব্লক",
    "walletConnectQr": "WalletConnect · QR কোড",
    "walletScanQr": "মোবাইল ওয়ালেট দিয়ে স্ক্যান করে সংযোগ অনুমোদন করুন।",
    "walletOpenMobile": "মোবাইল ওয়ালেট খুলুন",
    "walletConnectUnconfigured": "WalletConnect কনফিগার করা নেই। সাইট পরিচালকের সাথে যোগাযোগ করুন।",
    "walletConnectOriginDenied": "WalletConnect এই সাইটকে অনুমতি দেয়নি। সাইট পরিচালকের সাথে যোগাযোগ করুন।",
    "walletConnectUnavailable": "WalletConnect উপলব্ধ নেই। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।",
    "walletConnectExpired": "সংযোগের মেয়াদ শেষ। আবার চেষ্টা করুন।",
    "walletWrongNetwork": "এই নেটওয়ার্কে একটি অ্যাকাউন্ট বাছুন।",
    "approvalsTitle": "টোকেন অনুমতি",
    "approvalsIntro": "ERC-20 ও NFT অনুমতি দেখুন। বাতিল করতে মালিকের ওয়ালেট যুক্ত করুন।",
    "approvalRevoke": "বাতিল করুন",
    "approvalSpender": "অনুমোদিত ব্যয়কারী / অপারেটর",
    "approvalActive": "সক্রিয়",
    "approvalAll": "সব অনুমতি",
    "approvalRevoked": "নিষ্ক্রিয়",
    "approvalUnknown": "অবস্থা অনুপলব্ধ",
    "approvalStateUnavailable": "চেইনে অনুমতি যাচাই হয়নি। বাতিল করার আগে আবার চেষ্টা করুন।",
    "approvalUnlimited": "অসীম",
    "approvalRaw": "মূল একক",
    "approvalAccess": "অধিকার",
    "approvalCollection": "এই সংগ্রহের সব NFT",
    "approvalSingleNft": "শুধু এই NFT",
    "approvalUseWallet": "সংযুক্ত ওয়ালেট দেখুন",
    "approvalWrongOwner": "শুধু মালিকের ওয়ালেট এই অনুমতি বাতিল করতে পারে।",
    "approvalNone": "ইন্ডেক্স করা স্ট্যান্ডার্ড ইভেন্টে মিলে যাওয়া সক্রিয় অনুমতি নেই।",
    "approvalHistoryIncomplete": "ইতিহাস স্ক্যান অসম্পূর্ণ। বাকি অনুমতি দেখতে আবার চেষ্টা করুন।",
    "approvalScanned": "ব্লক {block} / {total} পর্যন্ত ইতিহাস যাচাই। বর্তমান অনুমতি পড়া হচ্ছে…",
    "approvalRevokeReview": "এই লেনদেন শুধু এই অনুমতি সরায়। ওয়ালেট নেটওয়ার্ক ফি নিশ্চিত করে।",
    "approvalScope": "ইন্ডেক্সের স্ট্যান্ডার্ড Approval / ApprovalForAll ইভেন্ট দিয়ে অনুসন্ধান; বর্তমান অবস্থা চেইন থেকে পড়া হয়। অস্ট্যান্ডার্ড কন্ট্রাক্ট, অনইন্ডেক্সড ইভেন্ট ও Permit2 এর বাইরে।",
    "liveHttp": "লাইভ · HTTP",
    "cancel": "বাতিল"
  },
  "ru": {
    "chooseWallet": "Выберите кошелёк",
    "browserWallet": "Кошелёк браузера",
    "noInstalledWallet": "Установленные кошельки не обнаружены.",
    "walletBrowserHelp": "На телефоне откройте эту страницу в браузере своего кошелька. На компьютере установите расширение кошелька и повторите попытку.",
    "approvalAmount": "Количество",
    "New blocks": "Новые блоки",
    "walletConnectQr": "WalletConnect · QR-код",
    "walletScanQr": "Отсканируйте мобильным кошельком и подтвердите подключение.",
    "walletOpenMobile": "Открыть мобильный кошелёк",
    "walletConnectUnconfigured": "WalletConnect не настроен. Обратитесь к администратору.",
    "walletConnectOriginDenied": "WalletConnect не разрешил этот сайт. Свяжитесь с администратором сайта.",
    "walletConnectUnavailable": "WalletConnect недоступен. Проверьте подключение и повторите попытку.",
    "walletConnectExpired": "Время подключения истекло. Повторите попытку.",
    "walletWrongNetwork": "Выберите аккаунт в этой сети.",
    "approvalsTitle": "Разрешения токенов",
    "approvalsIntro": "Просмотрите разрешения ERC-20 и NFT. Для отзыва подключите кошелёк владельца.",
    "approvalRevoke": "Отозвать",
    "approvalSpender": "Разрешённый получатель / оператор",
    "approvalActive": "Активные",
    "approvalAll": "Все разрешения",
    "approvalRevoked": "Неактивные",
    "approvalUnknown": "Состояние недоступно",
    "approvalStateUnavailable": "Не удалось проверить разрешение в сети. Повторите перед отзывом.",
    "approvalUnlimited": "Неограниченно",
    "approvalRaw": "базовых единиц",
    "approvalAccess": "Доступ",
    "approvalCollection": "Все NFT в коллекции",
    "approvalSingleNft": "Только этот NFT",
    "approvalUseWallet": "Проверить подключённый кошелёк",
    "approvalWrongOwner": "Только кошелёк владельца может отозвать эти разрешения.",
    "approvalNone": "В индексированных стандартных событиях нет подходящих активных разрешений.",
    "approvalHistoryIncomplete": "История проверена не полностью. Повторите для оставшихся разрешений.",
    "approvalScanned": "История проверена до блока {block} / {total}. Чтение текущих разрешений…",
    "approvalRevokeReview": "Транзакция удаляет только это разрешение. Кошелёк подтверждает комиссию сети.",
    "approvalScope": "Поиск по стандартным событиям Approval / ApprovalForAll в индексе; текущее состояние читается из сети. Нестандартные контракты, неиндексированные события и Permit2 не охвачены.",
    "liveHttp": "ОНЛАЙН · HTTP",
    "cancel": "Отмена"
  },
  "ja": {
    "chooseWallet": "ウォレットを選択",
    "browserWallet": "ブラウザのウォレット",
    "noInstalledWallet": "インストール済みウォレットが見つかりません。",
    "walletBrowserHelp": "スマートフォンではウォレット内のブラウザでこのページを開いてください。パソコンではウォレット拡張機能をインストールして再試行してください。",
    "approvalAmount": "数量",
    "New blocks": "新しいブロック",
    "walletConnectQr": "WalletConnect · QRコード",
    "walletScanQr": "モバイルウォレットで読み取り、接続を承認してください。",
    "walletOpenMobile": "モバイルウォレットを開く",
    "walletConnectUnconfigured": "WalletConnect が未設定です。サイト管理者に連絡してください。",
    "walletConnectOriginDenied": "WalletConnect はこのサイトを許可していません。サイト管理者に連絡してください。",
    "walletConnectUnavailable": "WalletConnect を利用できません。接続を確認して再試行してください。",
    "walletConnectExpired": "接続の有効期限が切れました。再試行してください。",
    "walletWrongNetwork": "このネットワークのアカウントを選択してください。",
    "approvalsTitle": "トークンの承認",
    "approvalsIntro": "ERC-20 と NFT の承認を確認。取り消すには所有者のウォレットを接続してください。",
    "approvalRevoke": "取り消す",
    "approvalSpender": "承認された支出者 / 操作者",
    "approvalActive": "有効",
    "approvalAll": "すべての承認",
    "approvalRevoked": "無効",
    "approvalUnknown": "状態を取得できません",
    "approvalStateUnavailable": "オンチェーンで承認を確認できません。取り消す前に再試行してください。",
    "approvalUnlimited": "無制限",
    "approvalRaw": "最小単位",
    "approvalAccess": "アクセス",
    "approvalCollection": "このコレクションのすべての NFT",
    "approvalSingleNft": "この NFT のみ",
    "approvalUseWallet": "接続中のウォレットを確認",
    "approvalWrongOwner": "所有者のウォレットのみがこれらの承認を取り消せます。",
    "approvalNone": "インデックスされた標準イベントに該当する有効な承認はありません。",
    "approvalHistoryIncomplete": "履歴の確認が未完了です。残りの承認を確認するには再試行してください。",
    "approvalScanned": "ブロック {block} / {total} まで履歴を確認。現在の承認を読み取り中…",
    "approvalRevokeReview": "この取引はこの承認のみを削除します。ネットワーク手数料はウォレットで確認してください。",
    "approvalScope": "標準の Approval / ApprovalForAll イベントから検出し、現在の状態をオンチェーンで確認します。非標準コントラクト、未登録イベント、Permit2 は対象外です。",
    "liveHttp": "ライブ · HTTP",
    "cancel": "キャンセル"
  }
};
